phase1: main.o board.o function.o all_user.o program.o
	g++ main.o board.o function.o all_user.o program.o -o phase1
main.o: main.cpp
	g++ -c main.cpp
program.o: program.cpp
	g++ -c program.cpp
function.o: function.cpp
	g++ -c function.cpp
board.o: board.cpp
	g++ -c board.cpp
all_user.o: all_user.cpp
	g++ -c all_user.cpp
